name: Frontend CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

defaults:
  run:
    shell: bash
    working-directory: frontend/

jobs:
  ci:
    name: Lint, build and test frontend
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 12

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn install

      - name: Lint project
        run: yarn lint

      - name: Test project
        run: yarn test
